FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=Javad.1384
ENV N8N_HOST=0.0.0.0
ENV NODE_ENV=production

# استفاده از پورت پیش‌فرض Render
ENV N8N_PORT=$PORT

EXPOSE $PORT
